### PR TITLE
Feature#81

### PR DESCRIPTION
**Pull request by DARucker**
This branch contains the first configurations for microservicies gateway and discovery

### CODE REVIEW

**Comment by DARucker** [comment]
added the configuration to asign port by eureka server

**Comment by DARucker** [comment]
test bug fixed

**Comment by anderson92zolis** [comment]
hello Dario, se ven errores el módulo de orden podrías mirarlo.

Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project ordersMicroservice: There are test failures.
Error:  
Error:  Please refer to /home/runner/work/ecommerceChallenge/ecommerceChallenge/ordersMicroservice/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :ordersMicroservice
Error: Process completed with exit code 1.

**Comment by DARucker** [comment]
fixed bug on OrderRepositoryText

**Pull request merged**
